* 数据融合
另一方面，如果使用不同类型的传感器，则需要将收集到的信息格式化为通用形式并在时域中对齐。
数据可以在到达系统时进行组合，也可以在融合过程中以定义的级别进行组合。
在融合系统中使用的数据的可靠性将取决于可用的传感器和用于数据融合的方法。
传感器的选择以及提高信息传输精度所需的传感器数量取决于当前的问题。
根据应用和所需的输出格式，可以使用不同类型的传感器。
表1简要概述了数据融合中常用的传感器。
传感器通常根据其物理性质进行分类。
它们通常基于电磁频谱、声波、触觉、气味或系统的绝对位置。
4.1 JDL过程模型
使用最广泛的框架之一是JDL数据融合框架。美国国防部实验室联合主任（JDL）数据融合小组最初在数据融合的早期定义了该系统。这个框架是为了帮助军事应用的发展而开发的。LLIAS和Hall[15]描述了可以进行数据融合的若干级别：
级别1，对象优化，尝试定位和标识对象。为此，通过融合对象的属性来报告全局情况来自多个资源。步骤包括此阶段:
表1常用传感器系统概述
传感器系统	输出格式
简单传感器	电压信号时间序列
红外线	图像
激光和照相机	图像
激光雷达	图像
磁共振	图像
光学的	图像
粒子图像测速（PIV）	图像
雷达	结构化时间序列
声纳	结构化时间序列
光谱学	频谱
超声波	结构化时间序列
X射线	图像
数据对齐、实体属性（即位置、速度、损坏类型、警报状态等）的预测、数据与实体的关联以及实体身份的细化。
第二级，态势评估试图从第1级提供的不完整信息构建一幅图像，即将重建的实体与观察到的事件（例如飞机飞越敌对领土）联系起来。
第三级，威胁评估根据可能的作战机会解释第二级的结果。它分析了采取一种行动胜过另一种行动的利弊。
过程细化（有时称为第4级）围绕这三个级别循环，以监控性能、确定信息增强的潜在来源，并优化传感器的分配。其他辅助支持系统包括用于存储和检索预处理数据和人机交互的数据管理系统。该模型过程的布局如图1所示。
JDL模型的分层分布允许将不同级别分解为子级别。这样，级别1可以进一步分为四个过程：数据对齐、数据关联、对象估计和对象标识。
–在数据对齐阶段，数据被处理到一个共同的空间和时间框架。
–数据关联可以进一步划分为同一变量的数据单元之间以及不同变量的数据单元之间执行的关联。在这个阶段，测量变量之间的接近程度。
–另一方面，对象估计可根据所采用的处理方法（顺序或批处理）、可用的参数识别和估计方程、最佳拟合函数准则以及所寻求的最佳拟合函数方法的优化进行细分。在这个阶段，数据融合中心估计物体的位置、速度或属性。
–对象标识阶段可细分为特征提取、标识声明和标识声明组合。在这一阶段，对对象的身份或分类进行预测。
在每一个最低的子层次，不同类型技术的映射可以很容易地分配，并根据手头的情况进行选择。
融合可以在融合中心的原始数据（集中处理）或预处理的本地融合数据（分散处理）上执行。还可以考虑混合数据融合系统，包括原始数据和预处理数据的集成。Paradis[16]提出了将前三个JDL级别组合到黑板数据结构中的方法。该框架通过充当融合中心的融合代理进一步与过程优化集成。
4.2汤姆普洛斯建筑
Thomopoulos[13]提出了一种由三个模块组成的数据融合架构，每个模块集成不同级别的数据或模块来集成数据，即：
–信号级融合，即由于缺乏描述被测现象的数学模型，通过学习进行数据关联。
–证据级融合，即根据统计模型和用户要求的评估（例如决策或假设测试）在不同推理级别组合数据。
–动态级融合，即借助现有数学模型实现数据融合。
取决于应用，这些级别的融合可以以顺序的方式实现，也可以互换地实现。如果目标是对机器进行连续的健康监测，则可以在信号级别进行数据组合，而如果需要根据信号做出广泛的决策，则需要应用高阶融合（例如证据融合）。图2给出了架构的概要。汤姆普洛斯强调，任何数据融合系统都应考虑实现预期性能的三个基本标准，即：
–关于融合信息的单调性。-关于所涉及的成本的单调性。
–对任何先验不确定性的稳健性。

图1 JDL数据融合框架

图2 Thomopoulos的数据融合架构图3 Luo和Kay的数据融合架构[16]

此外，数据融合系统中还应考虑诸如数据传输延迟、信道错误和其他通信方面的因素，以及数据的时空协同对准。
4.3    多传感器集成融合模型
罗和凯[17]介绍了一种基于多传感器集成的通用数据融合结构。在该系统中，不同来源的数据以分层的方式在嵌入式融合中心内进行组合。他们明确区分了多传感器集成和多传感器融合。前者是指使用多传感器信息来协助完成特定任务，而后者是指集成过程中存在数据实际组合的任何阶段。
图3显示了Luo和Kay同时表示多传感器集成和融合的框架图。从该图中，传感器级收集的数据以分层和顺序的方式传输到融合中心，在那里进行融合过程。图3所示的整个框架是多传感器集成的表示。在对n个传感器的输出进行处理后，在适当的情况下，借助信息系统，可以获得对测量现象的描述。合并一个包含相关数据库和图书馆的信息系统有助于融合进程。
当信息在不同的融合中心进行组合时，所需的表示级别从原始数据或信号级别增加到符号级别的数据更抽象的符号表示。表2显示了按信息表示分类的不同融合级别的比较。
4.4    基于行为知识的数据融合模型
Pau[18]描述了另一个基于行为知识形式主义的数据融合框架。从图4中可以看出，框架由许多基本阶段组成，这些阶段必须在建立总体输出之前完成。首先从原始数据中提取特征向量。然后将该向量对齐并与定义的特征相关联。然后在传感器属性和数据分析级别进行融合。最后一步是由一组行为规则组成，这些规则可以根据融合输出的最终表示来提取。该过程模型没有假设基于知识的系统中通常存在的黑板结构，而是使用包含三个表示级别的分层方法：
–对于每个传感器，最低级别包含一个向量空间，其中包含坐标尺寸和测量参数。
–下一级从这些向量中提取相关特征，并为其添加标签。
–第三个层次包含一组关于世界模型的形式，将特征向量与事件关联起来。
举例说明了人类检测和识别领域（如智能建筑、安全控制、监控）。
4.5瀑布模型
Harris[5]描述了数据融合社区常用的另一个层次结构示例，称为瀑布模型。该模型的表示如图5所示。从图中可以看出，数据流从数据层运行到决策层。传感器系统通过来自决策模块的反馈信息不断更新。反馈元件在重新校准、重新配置和数据收集方面为多传感器系统提供建议。
瀑布模型有三个层次的表示，如图5所示：
–在第1级，原始数据经过适当转换，以提供有关环境的所需信息-

表2数据融合层次特征
特点	信号电平	像素级	功能级别	符号
水平
信息表征水平	低	低	中等	高
感觉信息类型	多维信号	多个图像	从信号/图像中提取的特征	信号/图像的决策逻辑
感官信息模型	带噪声随机变量	像素上的随机过程	特征的非不变形式	不确定度符号

图4 Pau传感器数据融合过程
门特。为了完成这项任务，传感器的模型和测量现象的模型是必要的。这些模型可以基于实验分析或物理定律；
–第2级由这些特征的特征提取和融合组成。这些过程是为了获得关于数据的符号级推断。他们的目标是尽量减少数据内容，同时最大限度地增加所提供的信息。这个级别的输出是一个估计值的列表，其中包含与之相关的概率（和信念）；
–级别3将对象与事件关联。根据收集到的信息、可用的库和数据库以及人与人之间的交互作用，可以组合出可能的行动路线。
4.6    分布式黑板数据融合体系结构

图5瀑布模型图6分布式黑板数据融合
Schoess和Castore[9]描述了一个分布式黑板数据融合模型的例子。该模型如图6所示，其中两个传感器（s1和s2）连接到多个传感器（T）。这些传感器也有一个主管，负责控制如何处理相互冲突的传感器测量。这通常基于分配给每个传感器的置信水平。传感器组用于从分析中的物理系统（温度、压力等）获取尽可能多的信息。融合算法产生一个值F，它取决于两个传感器可用的数据。测量的置信度由监督员分配给每个传感器读数。这种方法可以定义为一个包含感官信息的数据库，并操作知识源之间的交流渠道。
4.7    综合数据融合模型
Bedworth和O&apos;Brien[19]描述了另一个称为综合模型的框架。这个过程模型是其他三个模型的混合体，称为boydloop、Dasarathy和瀑布模型。图7显示了这个框架的总体布局，它由四个主要模块组成。这些模块用于处理数据融合中的各种任务及其功能目标。作者将Boyd控制环描述为一个迭代过程，四个元素（观察、定向、决定和动作）在闭环中运行。另一方面，Dasarathy模型包含三个基本的数据融合层次：数据、特征和决策。
